base_dir: /home/ariasd/Downloads/LANTERN-main/evaluation/trans_tr_reasoning_dsc
dataset_path: /home/ariasd/Downloads/LANTERN-main/dataset/apr
dry_run: 0
gen:
  nattempt: 1
  nsample: 1
  temperature: 1.0
hist_top_k: 15
langs:
- C
- C#
- C++
- Go
- Java
- Javascript
- Kotlin
- PHP
- Python
- Ruby
- Rust
log_dir: logs
name: trans reasoning trans-repair DSC
num_proc: 17
repair:
  mode: vanilla
result:
  k: 1
state:
  action: start
  it: 0
termination:
  max_it: 11
translate:
  mode: reasoning
unfixed_k: 0
