base_dir: /home/ariasd/Downloads/LANTERN-main/evaluation/trans_tr_reasoning_dsc
dataset_path: /home/ariasd/Downloads/LANTERN-main/dataset/apr
dry_run: 0
gen:
  nattempt: 1
  nsample: 1
  temperature: 1.0
hist_top_k: 15
langs:
- Ruby
log_dir: logs
name: trans reasoning trans-repair DSC
num_proc: 17
repair:
  mode: vanilla
result:
  k: 1
state:
  action: translate
  it: 1
termination:
  max_it: 5
translate:
  mode: reasoning
unfixed_k: 0
